# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class UiFormSetUp(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(963, 485)
        Dialog.setMinimumSize(QtCore.QSize(963, 485))
        Dialog.setMaximumSize(QtCore.QSize(963, 485))
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 281, 351))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(150, 30, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 70, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 110, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 150, 113, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(150, 310, 113, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(150, 230, 113, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 190, 113, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 270, 113, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 121, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 121, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 121, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 121, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 121, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 121, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 270, 121, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 310, 121, 20))
        self.label_8.setObjectName("label_8")
        self.cancel_Button_2 = QtWidgets.QPushButton(Dialog)
        self.cancel_Button_2.setGeometry(QtCore.QRect(490, 410, 91, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.cancel_Button_2.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancel_Button_2.setFont(font)
        self.cancel_Button_2.setAutoFillBackground(True)
        self.cancel_Button_2.setObjectName("cancel_Button_2")
        self.confirm_Button = QtWidgets.QPushButton(Dialog)
        self.confirm_Button.setGeometry(QtCore.QRect(380, 410, 91, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.confirm_Button.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.confirm_Button.setFont(font)
        self.confirm_Button.setAutoFillBackground(True)
        self.confirm_Button.setObjectName("confirm_Button")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 20, 621, 351))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(20, 110, 121, 20))
        self.label_16.setObjectName("label_16")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(150, 110, 113, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 230, 121, 20))
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 121, 20))
        self.label_9.setObjectName("label_9")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(150, 150, 113, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(150, 30, 113, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 70, 121, 20))
        self.label_11.setObjectName("label_11")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(150, 190, 113, 21))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(20, 190, 121, 20))
        self.label_14.setObjectName("label_14")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(150, 310, 113, 21))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 30, 121, 20))
        self.label_10.setObjectName("label_10")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(20, 270, 121, 20))
        self.label_15.setObjectName("label_15")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(20, 310, 121, 20))
        self.label_12.setObjectName("label_12")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(150, 70, 113, 21))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(150, 230, 113, 21))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(150, 270, 113, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(280, 110, 121, 20))
        self.label_24.setObjectName("label_24")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(410, 270, 113, 21))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(280, 150, 121, 20))
        self.label_17.setObjectName("label_17")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_21.setGeometry(QtCore.QRect(410, 310, 113, 21))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(280, 190, 121, 20))
        self.label_22.setObjectName("label_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_23.setGeometry(QtCore.QRect(410, 190, 113, 21))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_20.setGeometry(QtCore.QRect(410, 30, 113, 21))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(280, 230, 121, 20))
        self.label_21.setObjectName("label_21")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_19.setGeometry(QtCore.QRect(410, 150, 113, 21))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_22.setGeometry(QtCore.QRect(410, 70, 113, 21))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_24.setGeometry(QtCore.QRect(410, 230, 113, 21))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(280, 270, 121, 20))
        self.label_23.setObjectName("label_23")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(280, 70, 121, 20))
        self.label_19.setObjectName("label_19")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(280, 30, 121, 20))
        self.label_18.setObjectName("label_18")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_18.setGeometry(QtCore.QRect(410, 110, 113, 21))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(280, 310, 121, 20))
        self.label_20.setObjectName("label_20")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 420, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(30, 400, 72, 15))
        self.label_25.setObjectName("label_25")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 420, 87, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(150, 400, 72, 15))
        self.label_26.setObjectName("label_26")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "参数设置"))
        self.label.setText(_translate("Dialog", "第1组电流设定值:"))
        self.label_2.setText(_translate("Dialog", "第2组电流设定值:"))
        self.label_3.setText(_translate("Dialog", "第3组电流设定值:"))
        self.label_4.setText(_translate("Dialog", "第4组电流设定值:"))
        self.label_5.setText(_translate("Dialog", "第5组电流设定值:"))
        self.label_6.setText(_translate("Dialog", "第6组电流设定值:"))
        self.label_7.setText(_translate("Dialog", "第7组电流设定值:"))
        self.label_8.setText(_translate("Dialog", "第8组电流设定值:"))
        self.cancel_Button_2.setText(_translate("Dialog", "取消"))
        self.confirm_Button.setText(_translate("Dialog", "确认"))
        self.groupBox_2.setTitle(_translate("Dialog", "判定参数"))
        self.label_16.setText(_translate("Dialog", "第3组电流上限值:"))
        self.label_13.setText(_translate("Dialog", "第6组电流上限值:"))
        self.label_9.setText(_translate("Dialog", "第4组电流上限值:"))
        self.label_11.setText(_translate("Dialog", "第2组电流上限值:"))
        self.label_14.setText(_translate("Dialog", "第5组电流上限值:"))
        self.label_10.setText(_translate("Dialog", "第1组电流上限值:"))
        self.label_15.setText(_translate("Dialog", "第7组电流上限值:"))
        self.label_12.setText(_translate("Dialog", "第8组电流上限值:"))
        self.label_24.setText(_translate("Dialog", "第3组电流下限值:"))
        self.label_17.setText(_translate("Dialog", "第4组电流下限值:"))
        self.label_22.setText(_translate("Dialog", "第5组电流下限值:"))
        self.label_21.setText(_translate("Dialog", "第6组电流下限值:"))
        self.label_23.setText(_translate("Dialog", "第7组电流下限值:"))
        self.label_19.setText(_translate("Dialog", "第2组电流下限值:"))
        self.label_18.setText(_translate("Dialog", "第1组电流下限值:"))
        self.label_20.setText(_translate("Dialog", "第8组电流下限值:"))
        self.comboBox.setItemText(0, _translate("Dialog", "255"))
        self.comboBox.setItemText(1, _translate("Dialog", "1"))
        self.comboBox.setItemText(2, _translate("Dialog", "0"))
        self.comboBox.setItemText(3, _translate("Dialog", "2"))
        self.comboBox.setItemText(4, _translate("Dialog", "3"))
        self.comboBox.setItemText(5, _translate("Dialog", "4"))
        self.comboBox.setItemText(6, _translate("Dialog", "5"))
        self.comboBox.setItemText(7, _translate("Dialog", "6"))
        self.comboBox.setItemText(8, _translate("Dialog", "7"))
        self.comboBox.setItemText(9, _translate("Dialog", "8"))
        self.comboBox.setItemText(10, _translate("Dialog", "9"))
        self.comboBox.setItemText(11, _translate("Dialog", "10"))
        self.comboBox.setItemText(12, _translate("Dialog", "11"))
        self.comboBox.setItemText(13, _translate("Dialog", "12"))
        self.comboBox.setItemText(14, _translate("Dialog", "13"))
        self.comboBox.setItemText(15, _translate("Dialog", "14"))
        self.comboBox.setItemText(16, _translate("Dialog", "15"))
        self.label_25.setText(_translate("Dialog", "设备地址"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "A2"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "A3"))
        self.label_26.setText(_translate("Dialog", "功能码"))

