# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uvdevice_ui_01.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(1064, 830)
        Form.setMinimumSize(QtCore.QSize(945, 791))
        Form.setAutoFillBackground(True)
        self.gridLayout_5 = QtWidgets.QGridLayout(Form)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBox_1 = QtWidgets.QGroupBox(Form)
        self.groupBox_1.setFlat(False)
        self.groupBox_1.setObjectName("groupBox_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.groupBox_1)
        self.verticalGroupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox.setSizePolicy(sizePolicy)
        self.verticalGroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.s2__receive_text = QtWidgets.QTextBrowser(self.verticalGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.s2__receive_text.setPalette(palette)
        self.s2__receive_text.setAutoFillBackground(True)
        self.s2__receive_text.setObjectName("s2__receive_text")
        self.gridLayout.addWidget(self.s2__receive_text, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.verticalGroupBox, 0, 0, 1, 1)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.groupBox_1)
        self.verticalGroupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalGroupBox_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.verticalGroupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.s3__send_text = QtWidgets.QTextEdit(self.verticalGroupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.s3__send_text.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.s3__send_text.setFont(font)
        self.s3__send_text.setAutoFillBackground(True)
        self.s3__send_text.setObjectName("s3__send_text")
        self.gridLayout_2.addWidget(self.s3__send_text, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.verticalGroupBox_2, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_1, 0, 1, 7, 1)
        self.formGroupBox1 = QtWidgets.QGroupBox(Form)
        self.formGroupBox1.setMinimumSize(QtCore.QSize(200, 50))
        self.formGroupBox1.setMaximumSize(QtCore.QSize(200, 50))
        self.formGroupBox1.setObjectName("formGroupBox1")
        self.label_3 = QtWidgets.QLabel(self.formGroupBox1)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 181, 21))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/uvdevice_config/uvdevice_bk_02.png"))
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.formGroupBox1, 5, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(Form)
        self.groupBox_10.setMinimumSize(QtCore.QSize(431, 501))
        self.groupBox_10.setMaximumSize(QtCore.QSize(431, 200000))
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 30, 91, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 72, 15))
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(80, 30, 91, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 72, 15))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 72, 15))
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(80, 30, 91, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 72, 15))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 72, 15))
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_7.setAutoFillBackground(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_13.setGeometry(QtCore.QRect(80, 30, 91, 21))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_14.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setGeometry(QtCore.QRect(10, 30, 72, 15))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 72, 15))
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.groupBox_7, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_5.setAutoFillBackground(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_15.setGeometry(QtCore.QRect(80, 30, 91, 21))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_16.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(10, 30, 72, 15))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(10, 60, 72, 15))
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_6.setAutoFillBackground(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_17.setGeometry(QtCore.QRect(80, 30, 91, 21))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_18.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 72, 15))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(10, 60, 72, 15))
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.groupBox_6, 2, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_9.setAutoFillBackground(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_19.setGeometry(QtCore.QRect(80, 30, 91, 21))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_20.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_19 = QtWidgets.QLabel(self.groupBox_9)
        self.label_19.setGeometry(QtCore.QRect(10, 30, 72, 15))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_9)
        self.label_20.setGeometry(QtCore.QRect(10, 60, 72, 15))
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.groupBox_9, 3, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_8.setAutoFillBackground(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_21.setGeometry(QtCore.QRect(80, 30, 91, 21))
        self.lineEdit_21.setAutoFillBackground(True)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_22.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_21 = QtWidgets.QLabel(self.groupBox_8)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 72, 15))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_8)
        self.label_22.setGeometry(QtCore.QRect(10, 60, 72, 15))
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.groupBox_8, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_10, 0, 2, 7, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setMinimumSize(QtCore.QSize(220, 241))
        self.groupBox_2.setMaximumSize(QtCore.QSize(220, 241))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.hex_receive = QtWidgets.QCheckBox(self.groupBox_2)
        self.hex_receive.setObjectName("hex_receive")
        self.gridLayout_6.addWidget(self.hex_receive, 0, 0, 1, 2)
        self.s2__clear_button = QtWidgets.QPushButton(self.groupBox_2)
        self.s2__clear_button.setMinimumSize(QtCore.QSize(107, 28))
        self.s2__clear_button.setMaximumSize(QtCore.QSize(107, 28))
        self.s2__clear_button.setObjectName("s2__clear_button")
        self.gridLayout_6.addWidget(self.s2__clear_button, 1, 0, 1, 2)
        self.hex_send = QtWidgets.QCheckBox(self.groupBox_2)
        self.hex_send.setObjectName("hex_send")
        self.gridLayout_6.addWidget(self.hex_send, 2, 0, 1, 2)
        self.s3__send_button = QtWidgets.QPushButton(self.groupBox_2)
        self.s3__send_button.setMinimumSize(QtCore.QSize(107, 28))
        self.s3__send_button.setMaximumSize(QtCore.QSize(107, 28))
        self.s3__send_button.setObjectName("s3__send_button")
        self.gridLayout_6.addWidget(self.s3__send_button, 3, 0, 1, 2)
        self.s3__clear_button = QtWidgets.QPushButton(self.groupBox_2)
        self.s3__clear_button.setMinimumSize(QtCore.QSize(107, 28))
        self.s3__clear_button.setMaximumSize(QtCore.QSize(107, 28))
        self.s3__clear_button.setObjectName("s3__clear_button")
        self.gridLayout_6.addWidget(self.s3__clear_button, 4, 0, 1, 2)
        self.timer_send_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.timer_send_cb.setMinimumSize(QtCore.QSize(87, 19))
        self.timer_send_cb.setMaximumSize(QtCore.QSize(87, 19))
        self.timer_send_cb.setObjectName("timer_send_cb")
        self.gridLayout_6.addWidget(self.timer_send_cb, 5, 0, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(72, 21))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(72, 21))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_6.addWidget(self.lineEdit_3, 6, 0, 1, 1)
        self.dw = QtWidgets.QLabel(self.groupBox_2)
        self.dw.setObjectName("dw")
        self.gridLayout_6.addWidget(self.dw, 6, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 4, 0, 1, 1)
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setMinimumSize(QtCore.QSize(200, 89))
        self.formGroupBox.setMaximumSize(QtCore.QSize(200, 89))
        self.formGroupBox.setObjectName("formGroupBox")
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setGeometry(QtCore.QRect(12, 27, 60, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit.setGeometry(QtCore.QRect(70, 27, 124, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.label_2.setGeometry(QtCore.QRect(12, 55, 60, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 55, 124, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.formGroupBox, 6, 0, 1, 1)
        self.formGroupBox_2 = QtWidgets.QGroupBox(Form)
        self.formGroupBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formGroupBox_2.sizePolicy().hasHeightForWidth())
        self.formGroupBox_2.setSizePolicy(sizePolicy)
        self.formGroupBox_2.setMinimumSize(QtCore.QSize(220, 353))
        self.formGroupBox_2.setMaximumSize(QtCore.QSize(220, 353))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.formGroupBox_2.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.formGroupBox_2.setFont(font)
        self.formGroupBox_2.setMouseTracking(False)
        self.formGroupBox_2.setTabletTracking(False)
        self.formGroupBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.formGroupBox_2.setAcceptDrops(False)
        self.formGroupBox_2.setFlat(False)
        self.formGroupBox_2.setObjectName("formGroupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.formGroupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.s1__lb_5 = QtWidgets.QLabel(self.formGroupBox_2)
        self.s1__lb_5.setObjectName("s1__lb_5")
        self.gridLayout_7.addWidget(self.s1__lb_5, 5, 0, 1, 1)
        self.s1__box_5 = QtWidgets.QComboBox(self.formGroupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.s1__box_5.setPalette(palette)
        self.s1__box_5.setObjectName("s1__box_5")
        self.s1__box_5.addItem("")
        self.gridLayout_7.addWidget(self.s1__box_5, 5, 1, 1, 1)
        self.s1__box_3 = QtWidgets.QComboBox(self.formGroupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.s1__box_3.setPalette(palette)
        self.s1__box_3.setObjectName("s1__box_3")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.gridLayout_7.addWidget(self.s1__box_3, 3, 1, 1, 1)
        self.s1__lb_4 = QtWidgets.QLabel(self.formGroupBox_2)
        self.s1__lb_4.setObjectName("s1__lb_4")
        self.gridLayout_7.addWidget(self.s1__lb_4, 4, 0, 1, 1)
        self.s1__box_4 = QtWidgets.QComboBox(self.formGroupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.s1__box_4.setPalette(palette)
        self.s1__box_4.setObjectName("s1__box_4")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.gridLayout_7.addWidget(self.s1__box_4, 4, 1, 1, 1)
        self.s1__lb_6 = QtWidgets.QLabel(self.formGroupBox_2)
        self.s1__lb_6.setObjectName("s1__lb_6")
        self.gridLayout_7.addWidget(self.s1__lb_6, 6, 0, 1, 1)
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox_2)
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.gridLayout_7.addWidget(self.s1__lb_1, 0, 0, 1, 1)
        self.s1__box_6 = QtWidgets.QComboBox(self.formGroupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.s1__box_6.setPalette(palette)
        self.s1__box_6.setObjectName("s1__box_6")
        self.s1__box_6.addItem("")
        self.gridLayout_7.addWidget(self.s1__box_6, 6, 1, 1, 1)
        self.open_button = QtWidgets.QPushButton(self.formGroupBox_2)
        self.open_button.setAutoFillBackground(True)
        self.open_button.setObjectName("open_button")
        self.gridLayout_7.addWidget(self.open_button, 7, 0, 1, 2)
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox_2)
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.gridLayout_7.addWidget(self.s1__lb_2, 1, 0, 1, 1)
        self.close_button = QtWidgets.QPushButton(self.formGroupBox_2)
        self.close_button.setObjectName("close_button")
        self.gridLayout_7.addWidget(self.close_button, 8, 0, 1, 2)
        self.setup_button = QtWidgets.QPushButton(self.formGroupBox_2)
        self.setup_button.setMinimumSize(QtCore.QSize(0, 0))
        self.setup_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.setup_button.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.setup_button.setFont(font)
        self.setup_button.setObjectName("setup_button")
        self.gridLayout_7.addWidget(self.setup_button, 9, 0, 1, 2)
        self.state_label = QtWidgets.QLabel(self.formGroupBox_2)
        self.state_label.setMinimumSize(QtCore.QSize(196, 34))
        self.state_label.setMaximumSize(QtCore.QSize(196, 34))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.state_label.setPalette(palette)
        self.state_label.setText("")
        self.state_label.setTextFormat(QtCore.Qt.AutoText)
        self.state_label.setScaledContents(True)
        self.state_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state_label.setObjectName("state_label")
        self.gridLayout_7.addWidget(self.state_label, 2, 0, 1, 2)
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox_2)
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.gridLayout_7.addWidget(self.s1__box_1, 0, 1, 1, 1)
        self.s1__lb_3 = QtWidgets.QLabel(self.formGroupBox_2)
        self.s1__lb_3.setObjectName("s1__lb_3")
        self.gridLayout_7.addWidget(self.s1__lb_3, 3, 0, 1, 1)
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.s1__box_2.setPalette(palette)
        self.s1__box_2.setObjectName("s1__box_2")
        self.gridLayout_7.addWidget(self.s1__box_2, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.formGroupBox_2, 0, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(220, 21))
        self.dateTimeEdit.setMaximumSize(QtCore.QSize(220, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.dateTimeEdit.setPalette(palette)
        self.dateTimeEdit.setAutoFillBackground(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_5.addWidget(self.dateTimeEdit, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_1.setTitle(_translate("Form", "收发数据区"))
        self.verticalGroupBox.setTitle(_translate("Form", "接受区"))
        self.verticalGroupBox_2.setTitle(_translate("Form", "发送区"))
        self.s3__send_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400; color:#00aa00;\">Hello Python! Hello World!.........</span></p></body></html>"))
        self.formGroupBox1.setTitle(_translate("Form", "serialstatus"))
        self.groupBox_10.setTitle(_translate("Form", "运行数据"))
        self.groupBox.setTitle(_translate("Form", "第1组电源"))
        self.label_4.setText(_translate("Form", "输出电压："))
        self.label_5.setText(_translate("Form", "输出电流："))
        self.groupBox_4.setTitle(_translate("Form", "第2组电源"))
        self.label_9.setText(_translate("Form", "输出电压："))
        self.label_10.setText(_translate("Form", "输出电流："))
        self.groupBox_3.setTitle(_translate("Form", "第3组电源"))
        self.label_11.setText(_translate("Form", "输出电压："))
        self.label_12.setText(_translate("Form", "输出电流："))
        self.groupBox_7.setTitle(_translate("Form", "第4组电源"))
        self.label_13.setText(_translate("Form", "输出电压："))
        self.label_14.setText(_translate("Form", "输出电流："))
        self.groupBox_5.setTitle(_translate("Form", "第5组电源"))
        self.label_15.setText(_translate("Form", "输出电压："))
        self.label_16.setText(_translate("Form", "输出电流："))
        self.groupBox_6.setTitle(_translate("Form", "第6组电源"))
        self.label_17.setText(_translate("Form", "输出电压："))
        self.label_18.setText(_translate("Form", "输出电流："))
        self.groupBox_9.setTitle(_translate("Form", "第7组电源"))
        self.label_19.setText(_translate("Form", "输出电压："))
        self.label_20.setText(_translate("Form", "输出电流："))
        self.groupBox_8.setTitle(_translate("Form", "第8组电源"))
        self.label_21.setText(_translate("Form", "输出电压："))
        self.label_22.setText(_translate("Form", "输出电流："))
        self.groupBox_2.setTitle(_translate("Form", "Hex/Txt"))
        self.hex_receive.setText(_translate("Form", "Hex接收"))
        self.s2__clear_button.setText(_translate("Form", "清除接收区"))
        self.hex_send.setText(_translate("Form", "Hex发送"))
        self.s3__send_button.setText(_translate("Form", "发送"))
        self.s3__clear_button.setText(_translate("Form", "清除发送区"))
        self.timer_send_cb.setText(_translate("Form", "定时发送"))
        self.lineEdit_3.setText(_translate("Form", "1000"))
        self.dw.setText(_translate("Form", "ms/次"))
        self.formGroupBox.setTitle(_translate("Form", "串口状态"))
        self.label.setText(_translate("Form", "已接收："))
        self.label_2.setText(_translate("Form", "已发送："))
        self.formGroupBox_2.setTitle(_translate("Form", "串口设置"))
        self.s1__lb_5.setText(_translate("Form", "校验位："))
        self.s1__box_5.setItemText(0, _translate("Form", "N"))
        self.s1__box_3.setItemText(0, _translate("Form", "9600"))
        self.s1__box_3.setItemText(1, _translate("Form", "115200"))
        self.s1__box_3.setItemText(2, _translate("Form", "2400"))
        self.s1__box_3.setItemText(3, _translate("Form", "4800"))
        self.s1__box_3.setItemText(4, _translate("Form", "14400"))
        self.s1__box_3.setItemText(5, _translate("Form", "19200"))
        self.s1__box_3.setItemText(6, _translate("Form", "38400"))
        self.s1__box_3.setItemText(7, _translate("Form", "57600"))
        self.s1__box_3.setItemText(8, _translate("Form", "76800"))
        self.s1__box_3.setItemText(9, _translate("Form", "12800"))
        self.s1__box_3.setItemText(10, _translate("Form", "230400"))
        self.s1__box_3.setItemText(11, _translate("Form", "460800"))
        self.s1__lb_4.setText(_translate("Form", "数据位："))
        self.s1__box_4.setItemText(0, _translate("Form", "8"))
        self.s1__box_4.setItemText(1, _translate("Form", "7"))
        self.s1__box_4.setItemText(2, _translate("Form", "6"))
        self.s1__box_4.setItemText(3, _translate("Form", "5"))
        self.s1__lb_6.setText(_translate("Form", "停止位："))
        self.s1__lb_1.setText(_translate("Form", "串口检测："))
        self.s1__box_6.setItemText(0, _translate("Form", "1"))
        self.open_button.setText(_translate("Form", "打开串口"))
        self.s1__lb_2.setText(_translate("Form", "串口选择："))
        self.close_button.setText(_translate("Form", "关闭串口"))
        self.setup_button.setText(_translate("Form", "参数设置"))
        self.s1__box_1.setText(_translate("Form", "检测串口"))
        self.s1__lb_3.setText(_translate("Form", "波特率："))

import uvdevice_app_config_rc
